// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/cd4debea25a280da0808d4ff2ca5a4bdb34bd28b/moment-duration-format/index.d.ts
declare namespace moment {
    interface Duration {
        format(template: string, precision?: string, settings?: any): string;
    }
}
